### ISSUE TITLE
Make `storj/browser` v3 compatible

### ISSUE THREAD

**Issue by montyanderson** [storjrd/iris#18]
In https://github.com/storj/browser/blob/main/src/components/FileBrowser.vue

Remove all references to `this` inside `v-if` and `v-on`. Is fine to reference `this` inside the `<script>` section.

```
<tr
	v-if="
		this.$store.state.files
			.createFolderInputShow === true
	"
>
```

should be

```
<tr
	v-if="
		$store.state.files
			.createFolderInputShow === true
	"
>
```

**Comment by gabedealmeida** [comment]
https://github.com/storj/browser/pull/93
